"""phase3_complaint_lifecycle_and_verification

Revision ID: c385ad786ce6
Revises: 78f480187bc2
Create Date: 2026-09-29 07:42:43.812474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c385ad786ce6'
down_revision: Union[str, Sequence[str], None] = '78f480187bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_status_history', sa.Column('evidence_attachment_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'complaint_status_history', 'complaint_attachments', ['evidence_attachment_id'], ['id'], ondelete='SET NULL')
    op.add_column('complaints', sa.Column('resolution_claimed_by_id', sa.String(length=36), nullable=True))
    op.add_column('complaints', sa.Column('resolution_evidence_attachment_id', sa.String(length=36), nullable=True))
    op.add_column('complaints', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('complaints', sa.Column('verified_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('complaints', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('verification_remarks', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'complaint_attachments', ['resolution_evidence_attachment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaints', 'users', ['verified_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaints', 'users', ['resolution_claimed_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('escalations', sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('escalations', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'escalations', 'users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_column('escalations', 'reviewed_at')
    op.drop_column('escalations', 'reviewed_by_user_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'verification_remarks')
    op.drop_column('complaints', 'verified_at')
    op.drop_column('complaints', 'verified_by_user_id')
    op.drop_column('complaints', 'verification_status')
    op.drop_column('complaints', 'resolution_evidence_attachment_id')
    op.drop_column('complaints', 'resolution_claimed_by_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaint_status_history', type_='foreignkey')
    op.drop_column('complaint_status_history', 'evidence_attachment_id')
    # ### end Alembic commands ###
