"""phase4_ai_audit_findings_and_reviews

Revision ID: eca52746b5a4
Revises: c385ad786ce6
Create Date: 2026-09-29 09:07:12.660708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca52746b5a4'
down_revision: Union[str, Sequence[str], None] = 'c385ad786ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('facts', sa.Text(), nullable=False),
    sa.Column('interpretations', sa.Text(), nullable=False),
    sa.Column('unresolved_questions', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_assessment', sa.String(length=50), nullable=False),
    sa.Column('rule_or_model_version', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_attachment_id'], ['complaint_attachments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_findings_complaint_id'), 'ai_audit_findings', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_findings_created_at'), 'ai_audit_findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_audit_findings_evidence_attachment_id'), 'ai_audit_findings', ['evidence_attachment_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_findings_finding_type'), 'ai_audit_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_ai_audit_findings_severity'), 'ai_audit_findings', ['severity'], unique=False)
    op.create_table('ai_audit_finding_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=False),
    sa.Column('amended_facts', sa.Text(), nullable=True),
    sa.Column('amended_interpretations', sa.Text(), nullable=True),
    sa.Column('amended_severity', sa.String(length=20), nullable=True),
    sa.Column('amended_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['ai_audit_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_finding_reviews_action'), 'ai_audit_finding_reviews', ['action'], unique=False)
    op.create_index(op.f('ix_ai_audit_finding_reviews_created_at'), 'ai_audit_finding_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_audit_finding_reviews_finding_id'), 'ai_audit_finding_reviews', ['finding_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_finding_reviews_reviewer_user_id'), 'ai_audit_finding_reviews', ['reviewer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_audit_finding_reviews_reviewer_user_id'), table_name='ai_audit_finding_reviews')
    op.drop_index(op.f('ix_ai_audit_finding_reviews_finding_id'), table_name='ai_audit_finding_reviews')
    op.drop_index(op.f('ix_ai_audit_finding_reviews_created_at'), table_name='ai_audit_finding_reviews')
    op.drop_index(op.f('ix_ai_audit_finding_reviews_action'), table_name='ai_audit_finding_reviews')
    op.drop_table('ai_audit_finding_reviews')
    op.drop_index(op.f('ix_ai_audit_findings_severity'), table_name='ai_audit_findings')
    op.drop_index(op.f('ix_ai_audit_findings_finding_type'), table_name='ai_audit_findings')
    op.drop_index(op.f('ix_ai_audit_findings_evidence_attachment_id'), table_name='ai_audit_findings')
    op.drop_index(op.f('ix_ai_audit_findings_created_at'), table_name='ai_audit_findings')
    op.drop_index(op.f('ix_ai_audit_findings_complaint_id'), table_name='ai_audit_findings')
    op.drop_table('ai_audit_findings')
    # ### end Alembic commands ###
